// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gimawoskyipbsanqolkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpbWF3b3NreWlwYnNhbnFvbGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODQ3ODUsImV4cCI6MjA3MzA2MDc4NX0.zP-cu1RKpopujEuCSIs4qW5GPHavNtSC0vgBztSuUmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});